### ISSUE TITLE
X_test_bin 

### ISSUE THREAD

**Issue by Jingyan95** [cms-L1TK/TrainTrackQuality#1]
https://github.com/cms-L1TK/TrainTrackQuality/blob/421e66c6f5938fba73afaeeff77a6b3b680b1b1d/DefaultModel/create_default_gbdt.py#L113-L116

The digitized testing set is created but never used. I was wondering if there is a reason behind it.

**Comment by cgsavard** [comment]
Nice catch, this variable isn't being used but it should be. Since the classifier is being trained on binned variables, it should also be tested on binned variables. I will go through and update this.

**Comment by cgsavard** [comment]
These changes are now reflected in the code.
